### ISSUE TITLE
Javascript: class not inheriting from Model

### ISSUE THREAD

**Issue by spartanrein** [DavidDuwaer/Coloquent#100]
Hi, I'm trying to use coloquent in our react project (using es6)
My code is as follows:

```
import {Model} from 'coloquent';

class AppModel extends Model
{
    static jsonApiBaseUrl = `${process.env.REACT_APP_API_URL}/api`
}

class Payment extends AppModel {
    static jsonApiType = 'payments'
}

const Payments = () => {
  let Payments = new Payment()
  useEffect(()=> {
    Payments.get()
  })
  return (
    <someComponent/>
  )
}
```

I'm getting an error `TypeError: Payments.get is not a function`
Not sure  what's causing this issue as we are running in es6.

Hope everyone's doing well given the current situation.  Thanks in advance for your help!

**Comment by DavidDuwaer** [comment]
Hi Rein,

Looks like there's a typo. Have you tried `Payment.get()` instead of `Payments.get()`?

**Comment by DavidDuwaer** [comment]
Correct usage in a React component would look like

```javascript
const Payments = () => {
  const [payments, setPayments] = useState();
  useEffect(
    () => Payment.get().then(response => setPayments(response.data)),
    [],
  );
  if (payments === undefined) return <>Loading</>;
  return <>
    {payments.map(payment => <div>payment!</div>)}
  </>;
}
```

**Comment by DavidDuwaer** [comment]
Let me know if it works!

**Comment by spartanrein** [comment]
Hi @David,

Thanks very much for your quick response!
Silly me, I was trying to instantiate the model.
It works great as you suggested.
