### ISSUE TITLE
Limit to `n` results with a `.limit(n)` method in the query

### ISSUE THREAD

**Issue by DavidDuwaer** [DavidDuwaer/Coloquent#22]

**Comment by filipedtristao** [comment]
Can you describe the functionality you expect in this feature? How will it work with pagination?

I want to do a PR for this, but didn't find anything in the https://jsonapi.org/.

**Comment by DavidDuwaer** [comment]
It would have to work such that, for queries with the clause `.limit(n)` in it, no matter what `n` is, it does not change the first result returned (unless `n=0`). So if we have a page size of 10, and I end the query with `.limit(4).get(2)`, I get what would globally be the 21st-24th result.

**Comment by filipedtristao** [comment]
I think this can be closed now.
