### ISSUE TITLE
Allow to override "page[]" part of pagination parameter names

### ISSUE THREAD

**Issue by DavidDuwaer** [DavidDuwaer/Coloquent#23]
As JSON API [indicates](http://jsonapi.org/format/#fetching-pagination), using a "page[]" base for the pagination parameters is [recommended](https://tools.ietf.org/html/rfc2119#section-3), not an obligation. Therefore, users should be able to override the pagination parameter names completely, and not just the part between the brackets of "page[]"

**Comment by johannesschobel** [comment]
can be closed, i guess

**Comment by DavidDuwaer** [comment]
Good one
