### ISSUE TITLE
Can't resolve 'dateformat', this.initHttpClient is not a function

### ISSUE THREAD

**Issue by IgorSzymanski** [DavidDuwaer/Coloquent#31]
Related to #7 
After removing dateformat from the dependencies, I get the error when fetching data from any model extending my BadeModel class after fresh Coloquent installation (using TypeScript).

```
ERROR in ./node_modules/coloquent/dist/Model.js
Module not found: Error: Can't resolve 'dateformat' in '***\node_modules\coloquent\dist'

```

My base model:
```
import { Model as BaseModel } from 'coloquent';

export default abstract class Model extends BaseModel {
	getJsonApiBaseUrl () {
		return 'http://api.localhost/api/'
	}

	getJsonApiType() { return this.jsonApiType }
}

```

After installing dateformat@3.0.3 manually, I get another error:
```
this.initHttpClient is not a function
    at Article.Model (***\node_modules\coloquent\dist\Model.js:13)
```

which I'm not sure how to solve.

My project's dependencies:
```
	"dependencies": {
		"buefy": "^0.6.5",
		"coloquent": "^0.8.2",
		"dateformat": "^3.0.3",
		"nuxt": "^1.4.0",
		"nuxt-class-component": "^1.2.0",
		"nuxt-property-decorator": "1.1.3"
	},
	"devDependencies": {
		"babel-eslint": "^8.2.1",
		"eslint": "^4.15.0",
		"eslint-friendly-formatter": "^3.0.0",
		"eslint-loader": "^1.7.1",
		"eslint-plugin-vue": "^4.0.0",
		"node-sass": "^4.8.3",
		"sass-loader": "^6.0.7",
		"ts-loader": "3.2.0",
		"typescript": "2.6.2"
	}
```

**Comment by DavidDuwaer** [comment]
I'll also fix this one. Thanks. I'll keep you updated. If you find more about this one don't hesitate to post here.

**Comment by igorszymanski** [comment]
It seems changing my BaseModel class to:
```
import { Model as BaseModel } from 'coloquent/dist/lib/Model';
import {PaginationStrategy} from "coloquent/dist/lib/PaginationStrategy";

export default abstract class Model extends BaseModel {
	getJsonApiBaseUrl () {
		return 'http://api.localhost/api/'
	}

	public static setPaginationStrategy(paginationStrategy: PaginationStrategy): void
	{
		Model.paginationStrategy = paginationStrategy;
	}
}

```
solved the latter issue (pretty much copied the code from the tests). I'll do some other real life testing and let you know.

**Comment by DavidDuwaer** [comment]
For several releases already, the typescript compilation hadn't run... This caused "dateformat" to still be required in `{Model} from 'coloquent/dist/Model'`, but not in `{Model} from 'coloquent/dist/lib/Model`. Reorganised a bit so that

1. Recompiling won't anymore be forgotten...
2. The "dist/lib" folder won't be published anymore

When we move to v1.0 we'll move to publishing such that the import path will be `{Model} from 'coloquent'` instead of `{Model} from 'coloquent/dist'`.
