### ISSUE TITLE
Eager fetching a relation for a collection

### ISSUE THREAD

**Issue by IgorSzymanski** [DavidDuwaer/Coloquent#36]
This line causes an unexpected behaviour: https://github.com/DavidDuwaer/Coloquent/blob/c25b9769c49ed04182e19ee71c69f479f219701d/src/response/RetrievalResponse.ts#L81

If I do:
```ts
let MyModels: MyModel[] = [] 

MyModel.with('relation').get()
.then(response => { MyModels = <MyModel[]>response.getData() })
```
with response from backend:
```json
{
	"data": [
		{
			"type": "my-models",
			"id": "1",
			"relationships": {
				"relation": {
					"data": {
						"type": "relations",
						"id": "3"
					}
				}
			}
		},
		{
			"type": "my-models",
			"id": "2",
			"relationships": {
				"relation": {
					"data": {
						"type": "relations",
						"id": "3"
					}
				}
			}
		},
	],
	"included": [
		{
			"type": "relations",
			"id": "3",
			"attributes": {
				"test": "my relation"
			}
		}
	]
}
```
and some of the side-loaded `'relation'` relations are shared between objects in the collection (like in the example `MyModel(id: 1)` and `MyModel(id: 2)` share the same relation `Relation(id: 3)`, the relation `MyModel.getRelation()` won't be empty for the first object in the array, unlike for the rest in the collection.

**Unexpected:**
```ts
MyModels[0].getRelation() // returns Relation(id: 3)
MyModels[1].getRelation() // returns empty object
```

**Expected:**
```ts
MyModels[0].getRelation() // returns Relation(id: 3)
MyModels[1].getRelation() // returns Relation(id: 3)
```

Changing the condition to
```ts
if (true) { // visit every doc only once 
```
or completely removing it solves the problem.

**Comment by DavidDuwaer** [comment]
Thanks for submitting an issue about it. I've added a new test class and a test for it, and fixed it. New release is up (v1.0.1)
