### ISSUE TITLE
Can't access static http client instance until a model has been instantiated.

### ISSUE THREAD

**Issue by nulldotpro** [DavidDuwaer/Coloquent#37]
Given an arbitrary model:
```js
import { Model } from 'coloquent';

class User extends Model {
  jsonApiType = 'users';
}
```
The `getHttpClient` method will return undefined until an instance of the model has been instantiated:
```js
User.getHttpClient(); // returns undefined

user = new User();
User.getHttpClient(); // returns the static http client
```
This prevents http client configuration ( i.e. #29 ) from occurring until an object has been instantiated.

**Comment by vblinden** [comment]
This is because the instance gets instaniated in the constructor. See the following code: https://github.com/DavidDuwaer/Coloquent/blob/master/src/httpclient/axios/AxiosHttpClient.ts#L12

Can you make a PR?

**Comment by belzaaron** [comment]
I'm going to be working on a PR for this.

**Comment by masterT** [comment]
This is now possible with the version `3.0.1-beta`.
