### ISSUE TITLE
How to associate models when creating?

### ISSUE THREAD

**Issue by joaoeduardo** [DavidDuwaer/Coloquent#38]
I tried this code:
```js
(async () => {
  try {
    let page = new Page()

    page.title = 'teste'

    await page.create()

    let schema = new Schema()

    schema.value = {
      type: 'object',
      properties: {
        title: {
          type: 'string',
          title: 'Título'
        },
        content: {
          type: 'string',
          title: 'Conteúdo'
        }
      }
    }

    schema.setRelation('page', page)

    await schema.create()
  } catch (err) {
    console.log(err)
  }
})()
```
But the request payload doesn't has a relationships key on data object.

**Comment by DavidDuwaer** [comment]
This is missing from the implementation. Good one! It should happen in [this file (model.ts)](https://github.com/DavidDuwaer/Coloquent/blob/master/src/Model.ts). See how the `payload` array is built on line 136 and line 184? Relations are missing. Do you want to add it?

**Comment by joaoeduardo** [comment]
I never contributed to any project, but I will try.

**Comment by joaoeduardo** [comment]
I would implement this way:
```js
let relationships = {};
for (let key in this.relations.toArray()) {
    relationships[key] = {
        data: {
            type: this.relations.get(key).getJsonApiType(),
            id: this.relations.get(key).id
        }
    };
}
let payload = {
    data: {
        type: this.getJsonApiType(),
        attributes: attributes,
        relationships: relationships
    }
};
```
But I realized that this would append the key "relationships" in all requests, not only in "belongs to" relationships. Would not it be interesting to create the "belongs to" relationship?

**Comment by johannesschobel** [comment]
this issue can be closed, i guess?
