### ISSUE TITLE
Are relationship links followed 

### ISSUE THREAD

**Issue by SpeedyMikeByrne** [DavidDuwaer/Coloquent#39]
I am trying to load in related data that is specified in the relationships links (See an example of the JSON API response below). Is this supported as I can't see any extra network requests being sent.
In the example below, Category hasMany Group, but when I try to getRelation('groups'), the result is always empty.

{
  "data": [
    {
      "type": "categories",
      "id": 3,
      "attributes": {
        "title": "Plant"
      },
      "relationships": {
        "groups": {
          "links": {
            "related": "/api/v1/categories/3/groups"
          }
        }
      }
    }
]
}

**Comment by Bernhard---H** [comment]
I just had a look at the response parsing part of this library: it looks like all links are ignored/discarded

**Comment by SpeedyMikeByrne** [comment]
Thanks for the response. It looks like the data needs to be in the relationship for it to be included in the getRelation call. I'll close this off.
