### ISSUE TITLE
Expand compatibility to other pagination implementations

### ISSUE THREAD

**Issue by DavidDuwaer** [DavidDuwaer/Coloquent#4]
Now Coloquent is only compatible with pagination using offset/limit style pagination, with parameter names 'offset' and 'limit'. It should also be compatible with pagenumber/pagesize style pagination, and with different parameter names in both pagination styles.

**Comment by DavidDuwaer** [comment]
It is logical to do this configuration by overriding a few static properties on Model. (e.g. paginationStyle, paginationOffsetVarname, paginationPagesizeVarname, paginationPagenumberVarname, paginationCountFrom1 (bool))

**Comment by milroyfraser** [comment]
Addressed #6
