### ISSUE TITLE
Bring names into conformity with JSON:API spec

### ISSUE THREAD

**Issue by kael-shipman** [DavidDuwaer/Coloquent#45]
I know this is a big job and probably not the highest of priorities, but technically what you're calling `JsonApiDoc` is actually a `Resource` (per the [spec](https://jsonapi.org/format/#document-resource-objects)). I see you've got another object called simply `Doc`, but it would be nice to bring these more into conformity with the spec. Also, `JsonApiStub` is `ResourceIdentifier` in the spec.

Anyway, like I said, probably not a big deal, but I figured I'd register the issue anyway.

**Comment by DavidDuwaer** [comment]
The Doc class is obsolete, I removed it.

You're right about the nomenclature, it should indeed be called a Resource. Thanks for pointing it out. I've pushed the fix to master
