### ISSUE TITLE
Expand compatibility to other filter syntaxes

### ISSUE THREAD

**Issue by DavidDuwaer** [DavidDuwaer/Coloquent#5]
Coloquent now translates filters ('where' clauses) to a `filter[<attr_name>]=<attr_value>` syntax. This syntax is however not specified by JSON API and therefore one should be able to override this target syntax with a custom one.

**Comment by milroyfraser** [comment]
# Suggestion

#### Query String Patterns

- Round brackets patterns
    `/article?filter[author]=eq(john)&filter[tags]=in(oop,typescript,javascript)`

- Colon patterns
    `/article?filter[author]=eq:john&filter[tags]=in:oop,typescript,javascript`

#### Operators

- **eq** operator (Equals) `?name=john` or `?name=eq(john)`  
- **ne** operator (Not Equals) `?status=ne(failed)`
- **gt** operator (Greater Than) `?score=gt(50)`
- **ge** operator (Greater Than or Equal) `?score=ge(50)`
- **lt** operator (Less Than) `?score=lt(50)`
- **le** operator (Less Than or Equal) `?score=le(50)`
- **in** operator (In) `?tags=oop,typescript,javascript` or `?tags=in(oop,typescript,javascript)` 
- **notin** operator (Not In) `?tags=notin(oop,javascript)`
- **like** operator (Like) `?title=like(foo%)`
- **ilike** operator (In case sentence Like) `?title=ilike(Foo%)`
- **between** operator (Between two values) `?age=between(18,45)`

**Comment by DavidDuwaer** [comment]
This has been resolved by @milroyfraser in b905ec4bc42582b3e32af4c4fd151b8a657b9692.
