### ISSUE TITLE
Error in created hook: "TypeError: Class constructor Model cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by ConsoleTVs** [DavidDuwaer/Coloquent#75]
![image](https://user-images.githubusercontent.com/6124435/76672584-22204600-659e-11ea-91fd-72afa2f339cf.png)

When I get a model and I type:

Model.get(), this is thrown.

Eg: Product.get()

**Comment by xyng** [comment]
I just encountered this issue too. Seems like it's not an actual bug in the library, but a misconfiguration of your build-system.
For me, it was my Typescript-Compiler being set to `es5`, despite it's output being passed to babel later on (for ... reasons).
Setting it to `es6` or `esnext` solves that problem.

See [this similar issue in sequelize for more info and possible solutions](https://github.com/sequelize/sequelize/issues/7840#issuecomment-317212324)

**Comment by ConsoleTVs** [comment]
I want to use this for my front-end, and seems I am unable to compile it correctly. I had to run it with babel to run it. And yet it's still missleading

**Comment by DavidDuwaer** [comment]
This issue has been noted before: #54. Given the StackOverflow answer I linked there, from a quick look of it seems that there is no way around the issue, so we should just update documentation. Which part of the readme/description/documentation is misleading? Let's continue discussion in the other issue.
