### ISSUE TITLE
`BelongsTo` relation?

### ISSUE THREAD

**Issue by maicol07** [DavidDuwaer/Coloquent#93]
Hi,
Is there a way to add an inverse relation, like Laravel `belongsTo`?
Thanks

**Comment by DavidDuwaer** [comment]
Using [the example here](https://laravel.com/docs/8.x/eloquent-relationships), this would only be possible if your API endpoint/resource corresponding to Phone actually has an "include=user" implemented. However, if this is the case, then you don't need a belongsTo, you can just use a hasOne/hasMany.

**Comment by DavidDuwaer** [comment]
Your endpoint would need to support filters on related items, e.g. `users?filter[phone.id]=123`, or something like that, in order for a belongsTo implementation to become possible.

**Comment by maicol07** [comment]
Thank you, I've fixed it using `hasOne`.

Closing for now...
