### ISSUE TITLE
No way to add Authorisation Headers?

### ISSUE THREAD

**Issue by RaymondAtivie** [DavidDuwaer/Coloquent#96]
There seems to be no way to add authorisation headers, or any headers at all to the model or a base model.

Some endpoints need authorisation and i don't see a way of adding the token to the undelying axios instance. 

Any pointers?

(new to using this package, and i've read through all of the Wiki)

**Comment by masterT** [comment]
Related to https://github.com/DavidDuwaer/Coloquent/issues/91. With this PR https://github.com/DavidDuwaer/Coloquent/pull/94 it will be possible to set an `HttpAdapter` as a _static_ property of a Model class.

**Comment by RaymondAtivie** [comment]
Can't wait for this to be merged. The major thing stopping me from using this package

**Comment by masterT** [comment]
The PR haa been merged, it's available with the version `3.0.1-beta`.
